'''
There are configure values.
'''
# packet structure size
PACKET_TYPE_SIZE = 1
SEQUENCE_NUMBER_SIZE = 4
PEER_ADDRESS_SIZE = 4
PEER_PORT_NUMBER_SIZE = 2
PAYLOAD_SIZE = 1013
# packet size is 1024
PACKET_SIZE = 1024

PACKET_TYPE_NONE = 0
PACKET_TYPE_DATA = 1
PACKET_TYPE_SYN = 2
PACKET_TYPE_SYN_ACK = 3
PACKET_TYPE_ACK = 4
PACKET_TYPE_TIME = 5

# default settings
SERVER_IP = 'localhost'
SERVER_PORT = 8007
ROUTER_IP = 'localhost'
ROUTER_PORT = 3000
WINDOW_SIZE = 5
TIME_OUT = 2
TIME_OUT_RECV = 30
TIME_ALIVE = 5

LISTENER = 100000
IS_FINI = b'1'
